[package]
name = "coot_os"
version = "0.1.0"
authors = ["RobertNiklasBock <robert-niklas.bock@tu-ilmenau.de>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.6.0"
